/* Generated by wayland-scanner 1.24.0 */

#ifndef WINGLESS_BLUR_V1_CLIENT_PROTOCOL_H
#define WINGLESS_BLUR_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_wingless_blur_v1 The wingless_blur_v1 protocol
 * @section page_ifaces_wingless_blur_v1 Interfaces
 * - @subpage page_iface_wingless_blur_manager_v1 - factory for blur region objects
 * - @subpage page_iface_wingless_blur_region_v1 - a single blur region within a surface
 */
struct wingless_blur_manager_v1;
struct wingless_blur_region_v1;
struct wl_surface;

#ifndef WINGLESS_BLUR_MANAGER_V1_INTERFACE
#define WINGLESS_BLUR_MANAGER_V1_INTERFACE
/**
 * @page page_iface_wingless_blur_manager_v1 wingless_blur_manager_v1
 * @section page_iface_wingless_blur_manager_v1_desc Description
 * @section page_iface_wingless_blur_manager_v1_api API
 * See @ref iface_wingless_blur_manager_v1.
 */
/**
 * @defgroup iface_wingless_blur_manager_v1 The wingless_blur_manager_v1 interface
 */
extern const struct wl_interface wingless_blur_manager_v1_interface;
#endif
#ifndef WINGLESS_BLUR_REGION_V1_INTERFACE
#define WINGLESS_BLUR_REGION_V1_INTERFACE
/**
 * @page page_iface_wingless_blur_region_v1 wingless_blur_region_v1
 * @section page_iface_wingless_blur_region_v1_desc Description
 * @section page_iface_wingless_blur_region_v1_api API
 * See @ref iface_wingless_blur_region_v1.
 */
/**
 * @defgroup iface_wingless_blur_region_v1 The wingless_blur_region_v1 interface
 */
extern const struct wl_interface wingless_blur_region_v1_interface;
#endif

#define WINGLESS_BLUR_MANAGER_V1_GET_BLUR_REGION 0
#define WINGLESS_BLUR_MANAGER_V1_DESTROY 1


/**
 * @ingroup iface_wingless_blur_manager_v1
 */
#define WINGLESS_BLUR_MANAGER_V1_GET_BLUR_REGION_SINCE_VERSION 1
/**
 * @ingroup iface_wingless_blur_manager_v1
 */
#define WINGLESS_BLUR_MANAGER_V1_DESTROY_SINCE_VERSION 1

/** @ingroup iface_wingless_blur_manager_v1 */
static inline void
wingless_blur_manager_v1_set_user_data(struct wingless_blur_manager_v1 *wingless_blur_manager_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) wingless_blur_manager_v1, user_data);
}

/** @ingroup iface_wingless_blur_manager_v1 */
static inline void *
wingless_blur_manager_v1_get_user_data(struct wingless_blur_manager_v1 *wingless_blur_manager_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) wingless_blur_manager_v1);
}

static inline uint32_t
wingless_blur_manager_v1_get_version(struct wingless_blur_manager_v1 *wingless_blur_manager_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) wingless_blur_manager_v1);
}

/**
 * @ingroup iface_wingless_blur_manager_v1
 */
static inline struct wingless_blur_region_v1 *
wingless_blur_manager_v1_get_blur_region(struct wingless_blur_manager_v1 *wingless_blur_manager_v1, struct wl_surface *surface)
{
	struct wl_proxy *id;

	id = wl_proxy_marshal_flags((struct wl_proxy *) wingless_blur_manager_v1,
			 WINGLESS_BLUR_MANAGER_V1_GET_BLUR_REGION, &wingless_blur_region_v1_interface, wl_proxy_get_version((struct wl_proxy *) wingless_blur_manager_v1), 0, NULL, surface);

	return (struct wingless_blur_region_v1 *) id;
}

/**
 * @ingroup iface_wingless_blur_manager_v1
 */
static inline void
wingless_blur_manager_v1_destroy(struct wingless_blur_manager_v1 *wingless_blur_manager_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) wingless_blur_manager_v1,
			 WINGLESS_BLUR_MANAGER_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) wingless_blur_manager_v1), WL_MARSHAL_FLAG_DESTROY);
}

#define WINGLESS_BLUR_REGION_V1_SET_REGION 0
#define WINGLESS_BLUR_REGION_V1_SET_RADIUS 1
#define WINGLESS_BLUR_REGION_V1_SET_TINT 2
#define WINGLESS_BLUR_REGION_V1_SET_REFRACTION_BAND 3
#define WINGLESS_BLUR_REGION_V1_SET_BLUR_AMOUNT 4
#define WINGLESS_BLUR_REGION_V1_DESTROY 5


/**
 * @ingroup iface_wingless_blur_region_v1
 */
#define WINGLESS_BLUR_REGION_V1_SET_REGION_SINCE_VERSION 1
/**
 * @ingroup iface_wingless_blur_region_v1
 */
#define WINGLESS_BLUR_REGION_V1_SET_RADIUS_SINCE_VERSION 1
/**
 * @ingroup iface_wingless_blur_region_v1
 */
#define WINGLESS_BLUR_REGION_V1_SET_TINT_SINCE_VERSION 1
/**
 * @ingroup iface_wingless_blur_region_v1
 */
#define WINGLESS_BLUR_REGION_V1_SET_REFRACTION_BAND_SINCE_VERSION 1
/**
 * @ingroup iface_wingless_blur_region_v1
 */
#define WINGLESS_BLUR_REGION_V1_SET_BLUR_AMOUNT_SINCE_VERSION 1
/**
 * @ingroup iface_wingless_blur_region_v1
 */
#define WINGLESS_BLUR_REGION_V1_DESTROY_SINCE_VERSION 1

/** @ingroup iface_wingless_blur_region_v1 */
static inline void
wingless_blur_region_v1_set_user_data(struct wingless_blur_region_v1 *wingless_blur_region_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) wingless_blur_region_v1, user_data);
}

/** @ingroup iface_wingless_blur_region_v1 */
static inline void *
wingless_blur_region_v1_get_user_data(struct wingless_blur_region_v1 *wingless_blur_region_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) wingless_blur_region_v1);
}

static inline uint32_t
wingless_blur_region_v1_get_version(struct wingless_blur_region_v1 *wingless_blur_region_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) wingless_blur_region_v1);
}

/**
 * @ingroup iface_wingless_blur_region_v1
 */
static inline void
wingless_blur_region_v1_set_region(struct wingless_blur_region_v1 *wingless_blur_region_v1, int32_t x, int32_t y, int32_t width, int32_t height)
{
	wl_proxy_marshal_flags((struct wl_proxy *) wingless_blur_region_v1,
			 WINGLESS_BLUR_REGION_V1_SET_REGION, NULL, wl_proxy_get_version((struct wl_proxy *) wingless_blur_region_v1), 0, x, y, width, height);
}

/**
 * @ingroup iface_wingless_blur_region_v1
 */
static inline void
wingless_blur_region_v1_set_radius(struct wingless_blur_region_v1 *wingless_blur_region_v1, uint32_t radius)
{
	wl_proxy_marshal_flags((struct wl_proxy *) wingless_blur_region_v1,
			 WINGLESS_BLUR_REGION_V1_SET_RADIUS, NULL, wl_proxy_get_version((struct wl_proxy *) wingless_blur_region_v1), 0, radius);
}

/**
 * @ingroup iface_wingless_blur_region_v1
 */
static inline void
wingless_blur_region_v1_set_tint(struct wingless_blur_region_v1 *wingless_blur_region_v1, uint32_t r, uint32_t g, uint32_t b, uint32_t a)
{
	wl_proxy_marshal_flags((struct wl_proxy *) wingless_blur_region_v1,
			 WINGLESS_BLUR_REGION_V1_SET_TINT, NULL, wl_proxy_get_version((struct wl_proxy *) wingless_blur_region_v1), 0, r, g, b, a);
}

/**
 * @ingroup iface_wingless_blur_region_v1
 */
static inline void
wingless_blur_region_v1_set_refraction_band(struct wingless_blur_region_v1 *wingless_blur_region_v1, uint32_t band)
{
	wl_proxy_marshal_flags((struct wl_proxy *) wingless_blur_region_v1,
			 WINGLESS_BLUR_REGION_V1_SET_REFRACTION_BAND, NULL, wl_proxy_get_version((struct wl_proxy *) wingless_blur_region_v1), 0, band);
}

/**
 * @ingroup iface_wingless_blur_region_v1
 */
static inline void
wingless_blur_region_v1_set_blur_amount(struct wingless_blur_region_v1 *wingless_blur_region_v1, uint32_t amount)
{
	wl_proxy_marshal_flags((struct wl_proxy *) wingless_blur_region_v1,
			 WINGLESS_BLUR_REGION_V1_SET_BLUR_AMOUNT, NULL, wl_proxy_get_version((struct wl_proxy *) wingless_blur_region_v1), 0, amount);
}

/**
 * @ingroup iface_wingless_blur_region_v1
 */
static inline void
wingless_blur_region_v1_destroy(struct wingless_blur_region_v1 *wingless_blur_region_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) wingless_blur_region_v1,
			 WINGLESS_BLUR_REGION_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) wingless_blur_region_v1), WL_MARSHAL_FLAG_DESTROY);
}

#ifdef  __cplusplus
}
#endif

#endif
