/* Generated by wayland-scanner 1.24.0 */

#ifndef WINGLESS_BLUR_V1_SERVER_PROTOCOL_H
#define WINGLESS_BLUR_V1_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_wingless_blur_v1 The wingless_blur_v1 protocol
 * @section page_ifaces_wingless_blur_v1 Interfaces
 * - @subpage page_iface_wingless_blur_manager_v1 - factory for blur region objects
 * - @subpage page_iface_wingless_blur_region_v1 - a single blur region within a surface
 */
struct wingless_blur_manager_v1;
struct wingless_blur_region_v1;
struct wl_surface;

#ifndef WINGLESS_BLUR_MANAGER_V1_INTERFACE
#define WINGLESS_BLUR_MANAGER_V1_INTERFACE
/**
 * @page page_iface_wingless_blur_manager_v1 wingless_blur_manager_v1
 * @section page_iface_wingless_blur_manager_v1_desc Description
 * @section page_iface_wingless_blur_manager_v1_api API
 * See @ref iface_wingless_blur_manager_v1.
 */
/**
 * @defgroup iface_wingless_blur_manager_v1 The wingless_blur_manager_v1 interface
 */
extern const struct wl_interface wingless_blur_manager_v1_interface;
#endif
#ifndef WINGLESS_BLUR_REGION_V1_INTERFACE
#define WINGLESS_BLUR_REGION_V1_INTERFACE
/**
 * @page page_iface_wingless_blur_region_v1 wingless_blur_region_v1
 * @section page_iface_wingless_blur_region_v1_desc Description
 * @section page_iface_wingless_blur_region_v1_api API
 * See @ref iface_wingless_blur_region_v1.
 */
/**
 * @defgroup iface_wingless_blur_region_v1 The wingless_blur_region_v1 interface
 */
extern const struct wl_interface wingless_blur_region_v1_interface;
#endif

/**
 * @ingroup iface_wingless_blur_manager_v1
 * @struct wingless_blur_manager_v1_interface
 */
struct wingless_blur_manager_v1_interface {
	/**
	 * create a new blur region for a surface
	 *
	 * 
	 */
	void (*get_blur_region)(struct wl_client *client,
				struct wl_resource *resource,
				uint32_t id,
				struct wl_resource *surface);
	/**
	 * destroy the manager, regions are unaffected
	 *
	 * 
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
};


/**
 * @ingroup iface_wingless_blur_manager_v1
 */
#define WINGLESS_BLUR_MANAGER_V1_GET_BLUR_REGION_SINCE_VERSION 1
/**
 * @ingroup iface_wingless_blur_manager_v1
 */
#define WINGLESS_BLUR_MANAGER_V1_DESTROY_SINCE_VERSION 1

/**
 * @ingroup iface_wingless_blur_region_v1
 * @struct wingless_blur_region_v1_interface
 */
struct wingless_blur_region_v1_interface {
	/**
	 * set the rectangle within the surface to apply blur to
	 *
	 * 
	 */
	void (*set_region)(struct wl_client *client,
			   struct wl_resource *resource,
			   int32_t x,
			   int32_t y,
			   int32_t width,
			   int32_t height);
	/**
	 * set blur radius in pixels
	 *
	 * 
	 */
	void (*set_radius)(struct wl_client *client,
			   struct wl_resource *resource,
			   uint32_t radius);
	/**
	 * set RGBA tint overlaid on the blur, values 0-255
	 *
	 * 
	 */
	void (*set_tint)(struct wl_client *client,
			 struct wl_resource *resource,
			 uint32_t r,
			 uint32_t g,
			 uint32_t b,
			 uint32_t a);
	/**
	 * set the refraction band width in pixels (default 20)
	 *
	 * 
	 */
	void (*set_refraction_band)(struct wl_client *client,
				    struct wl_resource *resource,
				    uint32_t band);
	/**
	 * set the blur intensity, value divided by 100 (e.g. 120 = 1.2, default 120)
	 *
	 * 
	 */
	void (*set_blur_amount)(struct wl_client *client,
				struct wl_resource *resource,
				uint32_t amount);
	/**
	 * destroy this blur region and remove the effect
	 *
	 * 
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
};


/**
 * @ingroup iface_wingless_blur_region_v1
 */
#define WINGLESS_BLUR_REGION_V1_SET_REGION_SINCE_VERSION 1
/**
 * @ingroup iface_wingless_blur_region_v1
 */
#define WINGLESS_BLUR_REGION_V1_SET_RADIUS_SINCE_VERSION 1
/**
 * @ingroup iface_wingless_blur_region_v1
 */
#define WINGLESS_BLUR_REGION_V1_SET_TINT_SINCE_VERSION 1
/**
 * @ingroup iface_wingless_blur_region_v1
 */
#define WINGLESS_BLUR_REGION_V1_SET_REFRACTION_BAND_SINCE_VERSION 1
/**
 * @ingroup iface_wingless_blur_region_v1
 */
#define WINGLESS_BLUR_REGION_V1_SET_BLUR_AMOUNT_SINCE_VERSION 1
/**
 * @ingroup iface_wingless_blur_region_v1
 */
#define WINGLESS_BLUR_REGION_V1_DESTROY_SINCE_VERSION 1

#ifdef  __cplusplus
}
#endif

#endif
