/* Generated by wayland-scanner 1.24.0 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wingless_glass_region_v1_interface;
extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *wingless_glass_v1_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	&wingless_glass_region_v1_interface,
	&wl_surface_interface,
};

static const struct wl_message wingless_glass_manager_v1_requests[] = {
	{ "get_blur_region", "no", wingless_glass_v1_types + 4 },
	{ "destroy", "", wingless_glass_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface wingless_glass_manager_v1_interface = {
	"wingless_glass_manager_v1", 1,
	2, wingless_glass_manager_v1_requests,
	0, NULL,
};

static const struct wl_message wingless_glass_region_v1_requests[] = {
	{ "set_region", "iiii", wingless_glass_v1_types + 0 },
	{ "set_radius", "u", wingless_glass_v1_types + 0 },
	{ "set_tint", "uuuu", wingless_glass_v1_types + 0 },
	{ "set_refraction_band", "u", wingless_glass_v1_types + 0 },
	{ "set_blur_amount", "u", wingless_glass_v1_types + 0 },
	{ "destroy", "", wingless_glass_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface wingless_glass_region_v1_interface = {
	"wingless_glass_region_v1", 1,
	6, wingless_glass_region_v1_requests,
	0, NULL,
};

